DisableStartupLog = false
DisableInterruptHandler = false
DisablePathCorrection = false
EnablePathEscape = false
FireMethodNotAllowed = true
DisableBodyConsumptionOnUnmarshal = false
DisableAutoFireStatusCode = false
DisableVersionChecker = false
TimeFormat = "Mon, 01 Jan 2006 15:04:05 GMT"
Charset = "UTF-8"

EnableOptimizations = false